* Identifier
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.
#+begin_src emacs-lisp
;; in config.el we just need to put one line
;; (org-bable-load-file (expand-file-name "<path of the org file>"))
(setq user-full-name "Kanishak Vaidya"
      user-mail-address "will@fill.later")
#+end_src

* Themes and Fonts
Doom exposes five (optional) variables for controlling fonts in Doom. Here are the three important ones:

+ `doom-font'
+ `doom-variable-pitch-font'
+ `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:
(setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "sans" :size 13))

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Source Code Pro" :size 15)
      doom-variable-pitch-font (font-spec :family "Source Code Pro" :size 15 :weight 'Bold)
      doom-big-font (font-spec :family "Hack" :size 17))
#+end_src

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:
#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src

Transparency can be set in emacs windows ref:emacswiki.org/emacs/TransparentEmacs
#+begin_src emacs-lisp
(set-frame-parameter (selected-frame) 'alpha '(98 97))
#+end_src

* Org Mode Configuration
If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!
Maths should also be highlighted in Org-mode, and by default codeblocks should tangle
#+begin_src emacs-lisp
(after! org
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
  (setq org-directory "~/.org/")
  (setq org-src-window-setup 'split-window-right)
  (setq org-highlight-latex-and-related '(latex script entities)))
#+end_src

This is the configuration for org-publish, that enable us to make HTML files from org documents
#+begin_src emacs-lisp
(setq org-publish-use-timestamps-flag nil)
(setq org-export-with-broken-links t)
(setq org-publish-project-alist
      '(("PMRF.progress"
         :base-directory "~/doc/sites/test-site/"
         :base-extension "org"
         :publishing-directory "~/doc/sites/test-site/html/"
         :recursive t
         :exclude "org-html-themes/.*"
         :publishing-function org-html-publish-to-html
         :headline-levels 4
         :auto-preamble t)))
#+end_src

* Other Configuration
Here are some additional functions/macros that could help you configure Doom:

- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to this file. Emacs searches the `load-path' when you load packages with `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over the highlighted symbol at press 'K' (non-evil users must press 'C-c c k'). This will open documentation for it, including demos of how they are used. You can also try 'gd' (or 'C-c c d') to jump to their definition and see how they are implemented.
** Default shell should be bash not zsh
#+begin_src emacs-lisp
(setq shell-file-name "/usr/bin/bash")
#+end_src

* Language Configurations
** LaTeX configuration
LaTeX show hedious super and subscripts. I want to see plain text and don't want to see ^v as a v hanging on air
#+begin_src emacs-lisp
(setq font-latex-fontify-script nil)
(add-to-list 'load-path "/home/keshav/doc/programs/latex/")
(require 'lsp-latex)
(with-eval-after-load "tex-mode"
 (add-hook 'tex-mode-hook 'lsp)
 (add-hook 'latex-mode-hook 'lsp))
;; For bibtex
(with-eval-after-load "bibtex"
 (add-hook 'bibtex-mode-hook 'lsp))
#+end_src

** Python Configuration
Pyright language Server
#+begin_src emacs-lisp
(use-package lsp-pyright
  :ensure t
  :hook (python-mode . (lambda ()
                          (require 'lsp-pyright)
                          (lsp))))  ; or lsp-deferred

#+end_src
