# Don't print a new line at the start of the prompt
add_newline = false

format="[$cmd_duration $directory](bold cyan)$git_branch$git_status$git_state$git_commit$character"
## Make prompt a single line instead of two lines
[line_break]
disabled = true

[character]
success_symbol = "[](#00dd00) "
error_symbol = "[](#ee0000) "

[directory]
home_symbol = "ॐ "
truncate_to_repo = false

[username]
show_always = true 
disabled = false
format = "[$user]($style)"

[fill]
symbol = " "
