# Don't print a new line at the start of the prompt
add_newline = false

format='\[[$hostname@ $directory](bold cyan)$git_branch$git_status$git_state$git_commit\] $character'
## Make prompt a single line instead of two lines
[line_break]
disabled = true

[character]
success_symbol = "[ॐ ](#00dd00)"
error_symbol = "[ॐ ](#ee0000)"
# 
# ॐ

[directory]
home_symbol = "~"
truncate_to_repo = false

[fill]
symbol = " "

[hostname]
ssh_only = false
ssh_symbol = '肋'
format = '[$ssh_symbol](bold purple)[$hostname](bold yellow) '
disabled = false
