# Don't print a new line at the start of the prompt
add_newline = false

format="""
[$directory](bold cyan)ॐ $git_branch$git_status$git_state$git_commit $fill $cmd_duration
$character
"""


## Make prompt a single line instead of two lines
[line_break]
disabled = false

[character]
success_symbol = "[❯](#00dd00)"
error_symbol = "[❯](#ee0000)"
vimcmd_symbol = "[❮](#00dd00)"

[directory]
home_symbol = "~"
truncate_to_repo = false

[username]
show_always = true 
disabled = false
format = "[$user]($style) "

[fill]
symbol = " "
