# Don't print a new line at the start of the prompt
add_newline = false

format="""
$directory$hostnameॐ $git_branch$git_status$git_state$git_commit $fill $cmd_duration
$character
"""
## Make prompt a single line instead of two lines
[line_break]
disabled = false

[character]
success_symbol = "[❯](#00dd00)"
error_symbol = "[❯](#ee0000)"
vimcmd_symbol = "[❮](#00dd00)"

[directory]
style = "bold cyan"
home_symbol = "~"
truncate_to_repo = false

[fill]
symbol = " "

[hostname]
ssh_only = true
ssh_symbol = '肋'
format = '[$ssh_symbol](bold purple)[$hostname](bold yellow) '
disabled = false
