[colors.bright]
black = "0x686868"
blue = "0x5454ff"
cyan = "0x54ffff"
green = "0x54ff54"
magenta = "0xff54ff"
red = "0xff5454"
white = "0xffffff"
yellow = "0xffff54"

[colors.normal]
black = "0x000000"
blue = "0x1818b2"
cyan = "0x18b2b2"
green = "0x18b218"
magenta = "0xe11ee1"
red = "0xfa4b4b"
white = "0xb2b2b2"
yellow = "0xb26818"

[colors.primary]
background = "0x000000"
foreground = "0x18f018"
